"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Mago_1 = require("./Mago");
var Guerrero_1 = require("./Guerrero");
var Arquero_1 = require("./Arquero");
var mago1 = new Mago_1.Mago('Gandalf', 100);
var guerrero1 = new Guerrero_1.Guerrero('Arthas', 250);
var arquero1 = new Arquero_1.Arquero('Legolas', 150);
console.log('--------------------------------------------------------');
mago1.atacar();
mago1.aumentarVida(50);
mago1.subirDeNivel();
mago1.defender();
mago1.subirDeNivel();
mago1.atacar();
mago1.reducirVida(25);
mago1.bajarDeNivel();
console.log('--------------------------------------------------------');
guerrero1.atacar();
guerrero1.aumentarVida(150);
guerrero1.subirDeNivel();
guerrero1.defender();
guerrero1.subirDeNivel();
guerrero1.atacar();
guerrero1.reducirVida(75);
guerrero1.bajarDeNivel();
console.log('--------------------------------------------------------');
arquero1.atacar();
arquero1.aumentarVida(50);
arquero1.subirDeNivel();
arquero1.defender();
arquero1.subirDeNivel();
arquero1.atacar();
arquero1.reducirVida(50);
arquero1.bajarDeNivel();
console.log('--------------------------------------------------------');
